"""Merge every data/sources/*.json (one file per church/source) into data/sermons.json.

Files starting with "_" are skipped. data/sources/manual.json is a good home for hand-entered sermons.
If two records share an "id", the later file wins (sources are read alphabetically, manual.json last).

Usage:  uv run tools/build_sermons.py && uv run tools/validate_data.py
"""

from __future__ import annotations

import json
from pathlib import Path

DATA = Path(__file__).resolve().parent.parent / "data"


def main() -> None:
    files = sorted(p for p in (DATA / "sources").glob("*.json") if not p.name.startswith("_"))
    files.sort(key=lambda p: p.name == "manual.json")
    merged: dict[str, dict] = {}
    for f in files:
        rows = json.loads(f.read_text())
        for i, r in enumerate(rows):
            merged[r.get("id") or f"{f.stem}-{i}"] = r
        print(f"{f.name}: {len(rows)}")
    sermons = sorted(merged.values(), key=lambda r: r.get("date", ""), reverse=True)
    (DATA / "sermons.json").write_text(
        json.dumps({"_note": "GENERATED by tools/build_sermons.py from data/sources/. Edit sources, not this file.",
                    "sermons": sermons}, indent=1, ensure_ascii=False) + "\n")
    print(f"-> data/sermons.json: {len(sermons)} sermons")


if __name__ == "__main__":
    main()
