"""Merge every data/sources/*.json (one file per church/source) into data/sermons.json.

Each record's "notes" (episode show notes) is split out into data/notes.json, keyed by sermon id,
so the site's first load stays small; the sermon page fetches notes on demand.

Files starting with "_" are skipped. data/sources/manual.json is a good home for hand-entered sermons.
If two records share an "id", the later file wins (sources are read alphabetically, manual.json last).

"study": list of book ids this sermon is a study of (teaches the passage in context, vs. a topical sermon that
uses it), from scraping/fit/fit_labels.json (scraping/fit/apply_fit.py). Omitted when empty.

Usage:  uv run tools/build_sermons.py && uv run tools/validate_data.py
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
FIT = ROOT / "scraping" / "fit" / "fit_labels.json"


def main() -> None:
    files = sorted(p for p in (DATA / "sources").glob("*.json") if not p.name.startswith("_"))
    files.sort(key=lambda p: p.name == "manual.json")
    merged: dict[str, dict] = {}
    for f in files:
        rows = json.loads(f.read_text())
        for i, r in enumerate(rows):
            merged[r.get("id") or f"{f.stem}-{i}"] = r
        print(f"{f.name}: {len(rows)}")
    notes = {i: r.pop("notes") for i, r in merged.items() if r.get("notes")}
    fit = json.loads(FIT.read_text()) if FIT.exists() else {}
    for i, r in merged.items():
        r.pop("study", None)
        books = [x["book"] for x in r.get("refs", [])]
        study = [b for b in dict.fromkeys(books) if fit.get(f"{i}|{b}", {}).get("study")]
        if study:
            r["study"] = study
    if fit:
        print(f"study labels: {sum(1 for r in merged.values() if r.get('study'))} sermons")
    sermons = sorted(merged.values(), key=lambda r: r.get("date", ""), reverse=True)
    (DATA / "sermons.json").write_text(
        json.dumps({"_note": "GENERATED by tools/build_sermons.py from data/sources/. Edit sources, not this file.",
                    "sermons": sermons}, indent=1, ensure_ascii=False) + "\n")
    print(f"-> data/sermons.json: {len(sermons)} sermons")
    (DATA / "notes.json").write_text(json.dumps(notes, ensure_ascii=False, separators=(",", ":")) + "\n")
    print(f"-> data/notes.json: {len(notes)} sermons with show notes")


if __name__ == "__main__":
    main()
